language: python

python:
  - 3.6

cache:
  pip: true

matrix:
  fast_finish: true
  include:
    - python: 2.7
      install:
        - pip install dnspython
        - pip install blinker 
        - pip install sleekxmpp
        - pip install pyasn1
        - pip install pyasn1_modules
      before_script:
        - pip install flake8
        - flake8 -job
      script:
        - python setup.py test
    - python: 3.6
      before_install:
        - pip install -r requirements.txt
      before_script:
        - flake8 -job
      script:
        - python setup.py test
